version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
  test-app:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Run Backend Unit Tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Build and Push Image
          command: |
            #!/bin/bash
            docker build -t karsajobs:latest .
            docker tag karsajobs:latest ghcr.io/alvitojordan/karsajobs:latest
            echo $GITHUB_PACKAGES_TOKEN | docker login ghcr.io -u alvitojordan --password-stdin
            docker push ghcr.io/alvitojordan/karsajobs:latest

workflows:
  version: 2
  karsajobs_workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - lint-dockerfile
            - test-app
