# Versi API yang digunakan
apiVersion: apps/v1

# Jenis objek yang dibuat. Dalam hal ini Deployment
kind: Deployment

# Metadata untuk objek Deployment
metadata:

  # Nama deployment
  name: karsajobs

  # Label yang digunakan untuk selector
  labels:
    app: karsajobs

# Spesifikasi deployment
spec:

  # Jumlah replica pod yang diinginkan
  replicas: 1

  # selector label untuk pod
  selector:
    matchLabels:
      app: karsajobs

  # Template untuk pod yang akan dibuat
  template:

    # Metadata untuk pod
    metadata:

      # Label yang diterapakn pada pod
      labels:
        app: karsajobs

    # Spesifikasi dari pod
    spec:

      # Container yang akan digunakan di pod
      containers:

        # Nama Container
        - name: karsajobs

          # Image Docker yang digunakan
          image: ghcr.io/alvitojordan/karsajobs:latest

          # menentukan kebijakan. IfNotPresent berarti image hanya akan diunduh bila tidak tersedia secara lokal
          imagePullPolicy: IfNotPresent

          # Port yang akan digunakan oleh container
          ports:
            - containerPort: 8080

          # List Environment Variabel 
          env:

              # Nama Environment Variable (APP_PORT)
            - name: APP_PORT

              # Value APP_PORT
              value: "8080"

              # Nama Environment Variable (MONGO_HOST)
            - name: MONGO_HOST

              # Value MONGO_HOST
              value: mongo-service

              # Nama Environment Variable (MONGO_USER)
            - name: MONGO_USER

              # Sumber nilai Environment Variabel
              valueFrom:

                # Referensi ke secret dengan nama "mongo-secret"
                secretKeyRef:

                  # Nama secret yang akan digunakan
                  name: mongo-secret

                  # Key dari secret untuk mendapatkan nilai dari variabel "MONGO_USER"
                  key: MONGO_ROOT_USERNAME

              # Nama Environment Variable (MONGO_USER)
            - name: MONGO_PASS

              # Sumber nilai Environment Variabel
              valueFrom:

                # Referensi ke secret dengan nama "mongo-secret"
                secretKeyRef:

                  # Nama secret yang akan digunakan
                  name: mongo-secret

                  # Key dari secret untuk mendapatkan nilai dari variabel "MONGO_PASS"
                  key: MONGO_ROOT_PASSWORD
