name: karsajobs-ui-ci
on:
  push:
    branches:
      - karsajobs-ui
    release:
      types: [published]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login GitHub Packages
        run: echo ${{ secrets.PACKAGES_TOKEN }} | docker login ghcr.io -u ${{secrets.USERNAME}} --password-stdin

      - name: lint-dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/alvitojordan/karsajobs-ui

      - name: build-app-karsajobs-ui
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}, ghcr.io/alvitojordan/karsajobs-ui:latest
